In [1]:
import numpy as np
np.random.rand(25)

array([0.48218624, 0.10882302, 0.47360986, 0.36750493, 0.66119956,
       0.67498366, 0.35230163, 0.31992013, 0.81971235, 0.83840564,
       0.36444289, 0.41750408, 0.96040701, 0.56337179, 0.85659886,
       0.05802119, 0.28099704, 0.3030651 , 0.34506209, 0.77149227,
       0.04997036, 0.01942514, 0.4080103 , 0.92074569, 0.75729388])

In [2]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [6]:
print(array[0:10,3:8])


[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [8]:
np.random.rand(100)

array([0.58440156, 0.76740606, 0.45375646, 0.68986611, 0.15702415,
       0.52839012, 0.87018612, 0.70357436, 0.4371929 , 0.0601726 ,
       0.01937102, 0.52565181, 0.87952404, 0.72766802, 0.14493575,
       0.54470071, 0.19869888, 0.86657179, 0.17044669, 0.43609959,
       0.57882864, 0.69733737, 0.79272632, 0.10078223, 0.03069095,
       0.43520289, 0.08862426, 0.50965209, 0.57050846, 0.75087907,
       0.66864185, 0.05053082, 0.7982433 , 0.04973678, 0.08140938,
       0.05631971, 0.67284395, 0.02088272, 0.0760292 , 0.89988768,
       0.05790467, 0.42028648, 0.49205355, 0.99222728, 0.34978784,
       0.11906326, 0.56458191, 0.19369791, 0.33069901, 0.54268986,
       0.38854494, 0.65400022, 0.61897942, 0.42828663, 0.94607275,
       0.40694802, 0.18403022, 0.49284095, 0.3691935 , 0.77313227,
       0.52182942, 0.34021847, 0.85875215, 0.00107048, 0.61718818,
       0.56625191, 0.82904388, 0.28709885, 0.49513152, 0.89571712,
       0.9055082 , 0.56948101, 0.10457658, 0.70040109, 0.19646

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))